name: Learn basic of GitHub Action
on:
  push:
    branches:
      -  main
jobs:        
  install-java:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install java
        run: |
          apk add --no-cache openjdk11-jdk
          java --version
